#!/usr/bin/env python3
# Project:   HyperI AI
# File:      tools/generate-rules.py
# Purpose:   Auto-generate compact rules files from structured source standards
#
# License:   Proprietary
# Copyright: (c) 2026 HYPERI PTY LIMITED
"""Generate compact rules files from structured source standards.

Usage:
    python tools/generate-rules.py [--check] [--verbose]

Options:
    --check     Validate only — exit non-zero if any file would change or is malformed.
                Used in CI to enforce structure compliance.
    --verbose   Print each file processed and any warnings.

Source file contract (enforced in --check mode):
    Every ## section header MUST be followed by at least one bullet point
    (a line starting with "- " or "* ") before the first ### subsection or
    the next ## section. Sections with no extractable bullets are a lint error.

Override mechanism:
    If a rules file contains the line "<!-- override: manual -->" anywhere in
    its content, the generator will not overwrite it. Use this for UNIVERSAL.md
    and ci.md which are hand-maintained.

Universal files:
    Source files with "universal: true" in their frontmatter are skipped —
    their key rules should be manually maintained in UNIVERSAL.md.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
STANDARDS_DIR = REPO_ROOT / "standards"
RULES_DIR = REPO_ROOT / "standards" / "rules"

SOURCE_DIRS = [
    STANDARDS_DIR / "languages",
    STANDARDS_DIR / "infrastructure",
    STANDARDS_DIR / "common",
]

GENERATED_MARKER = "<!-- generated by tools/generate-rules.py -->"
MANUAL_OVERRIDE = "<!-- override: manual -->"


# ---------------------------------------------------------------------------
# YAML frontmatter parsing (stdlib only)
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse YAML-ish frontmatter and return (meta_dict, body_text).

    Supports only simple key: value pairs and list items (- item).
    Returns ({}, full_text) if no frontmatter block found.
    """
    if not text.startswith("---"):
        return {}, text

    end = text.find("\n---", 3)
    if end == -1:
        return {}, text

    fm_block = text[3:end].strip()
    body = text[end + 4:].lstrip("\n")

    meta: dict = {}
    current_key: Optional[str] = None
    current_list: Optional[list] = None

    for line in fm_block.splitlines():
        list_match = re.match(r"^  - (.+)$", line)
        kv_match = re.match(r"^(\w[\w_-]*):\s*(.*)$", line)

        if list_match and current_key and current_list is not None:
            current_list.append(list_match.group(1).strip().strip('"').strip("'"))
        elif kv_match:
            key = kv_match.group(1)
            val = kv_match.group(2).strip().strip('"').strip("'")
            if val == "":
                current_key = key
                current_list = []
                meta[key] = current_list
            elif val.lower() == "true":
                meta[key] = True
                current_key = None
                current_list = None
            elif val.lower() == "false":
                meta[key] = False
                current_key = None
                current_list = None
            else:
                meta[key] = val
                current_key = None
                current_list = None

    return meta, body


# ---------------------------------------------------------------------------
# Rule extraction
# ---------------------------------------------------------------------------

def extract_rules(body: str, source_path: Path, strict: bool) -> tuple[str, list[str]]:
    """Extract ## section headers and their direct bullet points.

    Returns (extracted_markdown, list_of_warnings).
    Bullets are lines starting with "- " or "* " that appear BEFORE the first
    ### subsection or the next ## section in each block.

    In strict mode, a section with no bullets is added to warnings.
    """
    warnings: list[str] = []
    sections: list[str] = []

    # Split on ## headings (not ###)
    parts = re.split(r"^(## .+)$", body, flags=re.MULTILINE)

    # parts[0] is preamble before first ##, then alternates: heading, content
    i = 1
    while i < len(parts) - 1:
        heading = parts[i].strip()
        content = parts[i + 1]
        i += 2

        bullets: list[str] = []
        for line in content.splitlines():
            # Stop at a ### subsection
            if line.startswith("### "):
                break
            # Stop at a horizontal rule
            if line.startswith("---"):
                break
            if line.startswith("- ") or line.startswith("* "):
                bullets.append(line)

        if not bullets:
            msg = f"{source_path.name}: section '{heading}' has no extractable bullets"
            warnings.append(msg)
            # In non-strict mode: skip empty sections rather than include them
            continue

        sections.append(heading)
        sections.extend(bullets)
        sections.append("")

    return "\n".join(sections).rstrip() + "\n", warnings


# ---------------------------------------------------------------------------
# Rules file generation
# ---------------------------------------------------------------------------

def build_rules_file(meta: dict, body: str, source_rel: str) -> str:
    """Build the full content of a generated rules file."""
    lines = [f"---"]
    lines.append(f"# {GENERATED_MARKER}")
    lines.append(f"# Source: standards/{source_rel}")
    lines.append(f"# DO NOT EDIT MANUALLY — regenerate with: python tools/generate-rules.py")

    rule_paths = meta.get("rule_paths") or meta.get("paths", [])
    if rule_paths:
        lines.append("paths:")
        for p in rule_paths:
            lines.append(f'  - "{p}"')

    detect_markers = meta.get("detect_markers", [])
    if detect_markers:
        lines.append("detect_markers:")
        for m in detect_markers:
            lines.append(f'  - "{m}"')

    source_ref = meta.get("name", source_rel.replace("/", "-").replace(".md", ""))
    lines.append(f"source: {source_rel}")
    lines.append("---")
    lines.append("")
    lines.append(body)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Stem → rules filename mapping
# ---------------------------------------------------------------------------

_STEM_MAP = {
    "SQL-CLICKHOUSE": "clickhouse-sql",
    "K8S": "k8s",
    "PKI": "pki",
    "CPP": "cpp",
}


def source_to_rules_name(source_path: Path) -> str:
    """Convert source filename to rules filename (lowercase kebab)."""
    stem = source_path.stem  # e.g. "SQL-CLICKHOUSE", "RUST", "DOCKER"
    if stem in _STEM_MAP:
        return f"{_STEM_MAP[stem]}.md"
    return f"{stem.lower()}.md"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def process_file(
    source_path: Path,
    check: bool,
    verbose: bool,
) -> tuple[int, int]:
    """Process one source file. Returns (errors, warnings) counts."""
    errors = 0
    warnings_count = 0

    text = source_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)

    if not meta:
        if verbose:
            print(f"  SKIP {source_path.name} — no frontmatter")
        return 0, 0

    # Universal files: key rules go into UNIVERSAL.md manually
    if meta.get("universal"):
        if verbose:
            print(f"  SKIP {source_path.name} — universal: true (handled in UNIVERSAL.md)")
        return 0, 0

    # Determine target rules file
    rules_name = source_to_rules_name(source_path)
    rules_path = RULES_DIR / rules_name

    # Check for manual override
    if rules_path.exists():
        existing = rules_path.read_text(encoding="utf-8")
        if MANUAL_OVERRIDE in existing:
            if verbose:
                print(f"  SKIP {rules_name} — manual override")
            return 0, 0

    # Extract rules from body
    extracted, section_warnings = extract_rules(body, source_path, strict=check)
    for w in section_warnings:
        print(f"  WARN {w}", file=sys.stderr)
        warnings_count += 1
        if check:
            errors += 1

    if not extracted.strip():
        print(f"  WARN {source_path.name} — no rules extracted (empty output)", file=sys.stderr)
        warnings_count += 1
        if check:
            errors += 1
        return errors, warnings_count

    # Build relative source path for the header comment
    try:
        source_rel = source_path.relative_to(STANDARDS_DIR).as_posix()
    except ValueError:
        source_rel = source_path.name

    new_content = build_rules_file(meta, extracted, source_rel)

    if check:
        if rules_path.exists():
            existing = rules_path.read_text(encoding="utf-8")
            # Compare ignoring the generated marker comment line (has no semantic value)
            if existing != new_content:
                print(f"  FAIL {rules_name} — out of date (run generate-rules.py)", file=sys.stderr)
                errors += 1
            elif verbose:
                print(f"  OK   {rules_name}")
        else:
            print(f"  FAIL {rules_name} — missing (run generate-rules.py)", file=sys.stderr)
            errors += 1
    else:
        rules_path.write_text(new_content, encoding="utf-8")
        if verbose:
            warn_str = f" ({warnings_count} warnings)" if warnings_count else ""
            print(f"  GEN  {rules_name}{warn_str}")

    return errors, warnings_count


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    verbose = "--verbose" in args or "-v" in args

    total_errors = 0
    total_warnings = 0
    total_processed = 0

    for source_dir in SOURCE_DIRS:
        if not source_dir.is_dir():
            continue
        for source_path in sorted(source_dir.glob("*.md")):
            errors, warns = process_file(source_path, check=check, verbose=verbose)
            total_errors += errors
            total_warnings += warns
            if not (errors == 0 and warns == 0 and not verbose):
                pass  # already printed
            total_processed += 1

    if verbose or total_errors:
        mode = "CHECK" if check else "GENERATE"
        print(f"\n[{mode}] {total_processed} files | {total_errors} errors | {total_warnings} warnings")

    return 1 if total_errors else 0


if __name__ == "__main__":
    sys.exit(main())
