#!/usr/bin/env python3
# Project:   HyperI AI
# File:      tools/generate-rules.py
# Purpose:   LLM-compress full source standards into compact rules files
#
# License:   Proprietary
# Copyright: (c) 2026 HYPERI PTY LIMITED
"""Generate compact rules files from source standards via LLM compression.

Usage:
    python tools/generate-rules.py [--check] [--verbose] [--force] [--file FILE]

Options:
    --check     Validate frontmatter only — does NOT regenerate or
                compare content. Used in CI to enforce structure.
    --verbose   Print each file processed and compression stats.
    --force     Regenerate ALL files (default: only changed since HEAD~1).
    --file FILE Process only the source file matching FILE (e.g. RUST.md).

Default behaviour (no flags):
    Only processes source files changed/added since HEAD~1 (git diff).
    Deletes compact rules for removed source files.
    Safe and cheap to run on every push.

LLM compression:
    Sends each full source standard to Claude (Opus 4.6) with a compression
    prompt that produces high-quality compact rules with code examples,
    wrong/right pairs, and substitution tables.

    Requires ANTHROPIC_API_KEY in environment or .env file.
    If the API key is missing or the call fails, the file is skipped with a
    warning — existing compact rules are never deleted on failure.

Universal files:
    All source files in standards/{languages,infrastructure,universal}/ are
    processed. No files are skipped based on frontmatter flags.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
STANDARDS_DIR = REPO_ROOT / "standards"
RULES_DIR = REPO_ROOT / "standards" / "rules"

# Directories processed for INDIVIDUAL per-topic compact rules.
# universal/ is NOT here — it only feeds the combined universal.md
# via process_universal_combined().
SOURCE_DIRS = [
    STANDARDS_DIR / "languages",
    STANDARDS_DIR / "infrastructure",
]

# universal/ is tracked separately for delta detection and combined generation.
UNIVERSAL_SOURCE_DIR = STANDARDS_DIR / "universal"

GENERATED_MARKER = "<!-- generated by tools/generate-rules.py -->"


# ---------------------------------------------------------------------------
# YAML frontmatter parsing (stdlib only)
# ---------------------------------------------------------------------------


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse YAML-ish frontmatter and return (meta_dict, body_text)."""
    if not text.startswith("---"):
        return {}, text

    end = text.find("\n---", 3)
    if end == -1:
        return {}, text

    fm_block = text[3:end].strip()
    body = text[end + 4 :].lstrip("\n")

    meta: dict = {}
    current_key: Optional[str] = None
    current_list: Optional[list] = None

    for line in fm_block.splitlines():
        list_match = re.match(r"^  - (.+)$", line)
        kv_match = re.match(r"^(\w[\w_-]*):\s*(.*)$", line)

        if list_match and current_key and current_list is not None:
            current_list.append(list_match.group(1).strip().strip('"').strip("'"))
        elif kv_match:
            key = kv_match.group(1)
            val = kv_match.group(2).strip().strip('"').strip("'")
            if val == "":
                current_key = key
                current_list = []
                meta[key] = current_list
            elif val.lower() == "true":
                meta[key] = True
                current_key = None
                current_list = None
            elif val.lower() == "false":
                meta[key] = False
                current_key = None
                current_list = None
            else:
                meta[key] = val
                current_key = None
                current_list = None

    return meta, body


# ---------------------------------------------------------------------------
# LLM compression (Anthropic Claude API)
# ---------------------------------------------------------------------------

_LLM_COMPRESS_PROMPT = """\
You are a technical standards compressor. Compress this full coding \
standards document into a compact rules file optimised for LLM system prompts.

OUTPUT: Only the compressed markdown. No preamble, no explanation, no wrapping.

FORMAT (these produce better LLM instruction-following):
- ❌/✅ pairs for wrong→right patterns — anchor better than abstract bullets
- SHORT code blocks (3-8 lines) for critical patterns — the consuming LLM copies these
- "Use This, Not That" tables: | ❌ Don't | ✅ Do | Why |
- Max 5-7 bullets per section. Dense walls get skimmed.
- Tables over prose. Directives over explanations.
- Front-load the most common AI mistakes.
- No motivational language. Direct imperatives only.

CONTENT — CRITICAL:
- KEEP every named tool, crate, library, CLI command, config file
- KEEP every concrete pattern (shutdown, backpressure, config, health, etc.)
- KEEP all deprecated crate/API warnings and version-specific info
- KEEP build/CI commands and required tooling
- SHORTEN but do NOT delete sections — every ## topic in the source \
should appear in the output
- CUT explanatory prose, motivation, history
- CUT long code examples (shorten to 3-8 lines)
- CUT anything already in UNIVERSAL.md (git, file headers, basic security)

The output is injected into a 200K LLM context window. Be concise \
but preserve ALL actionable patterns and named tools.

SOURCE DOCUMENT:
"""

_UNIVERSAL_COMBINED_PROMPT = """\
You are a technical standards compressor. You are given MULTIPLE coding \
standards documents concatenated together. Compress them ALL into a SINGLE \
compact rules file that serves as the universal baseline for ALL coding work.

This output is the ONLY rules file guaranteed to load on EVERY conversation, \
regardless of which files or languages the developer is working with. It must \
be a self-contained reference for the most important cross-cutting rules.

OUTPUT: Only the compressed markdown. No preamble, no explanation, no wrapping.

LENGTH REQUIREMENT: Output MUST be 800-1000 lines of markdown. \
This is a HARD FLOOR — outputs under 700 lines are rejected as too brief. \
You are compressing 8,000+ lines of source. A 500-line output loses too \
much. An 800-1000 line output preserves the actionable detail that \
prevents AI coding mistakes. This is the universal baseline — \
language-specific and infrastructure-specific rules load separately.

FORMAT (these produce better LLM instruction-following):
- Start with a "# HyperI Universal Coding Rules" heading
- ❌/✅ pairs for wrong→right patterns — anchor better than abstract bullets
- SHORT code blocks (3-8 lines) for critical patterns
- "Use This, Not That" tables: | ❌ Don't | ✅ Do | Why |
- Max 5-7 bullets per section. Dense walls get skimmed.
- Tables over prose. Directives over explanations.
- Front-load the most common AI mistakes.
- No motivational language. Direct imperatives only.

CONTENT — CRITICAL:
- Every source document's KEY rules must appear — no document should be \
entirely dropped
- KEEP concrete patterns: config cascade, error handling, git conventions, \
testing policy, security rules, mocks prohibition, logging standards
- KEEP all ❌/✅ pairs and "Use This Not That" tables from sources
- KEEP the commit type table and branch naming conventions
- KEEP the .env quoting rules and config cascade priority order
- KEEP the no-mocks policy core rule and what to use instead
- KEEP SOLID/DRY/KISS/YAGNI key summaries (1-3 lines each, not full examples)
- KEEP AI conduct rules (no placeholders, three-iteration rule, SEP fields)
- KEEP the bleeding-edge dependency table (stale → current replacements)
- KEEP file header template
- KEEP character/emoji policy summary (log levels, permitted symbols)
- SHORTEN but do NOT delete any topic — every source document should \
have representation in the output
- CUT lengthy multi-language examples (keep ONE short example per pattern)
- CUT full SOLID code examples (keep the principle + 1-2 line summary)
- CUT detailed CI workflow steps (keep the commands and triggers)
- CUT exhaustive issue tracking templates (keep the mandatory fields)
- CUT PKI/certificate details beyond the key rules
- CUT design principle extended examples (keep the tables)

The output is injected into a 200K LLM context window alongside \
language-specific rules. Budget: 10,000-12,000 tokens (~700-900 lines). \
DO NOT under-produce — a 400-line output wastes budget headroom. \
Preserve ALL actionable patterns, ❌/✅ pairs, concrete code examples, \
and multi-language patterns. Keep short code blocks for each major topic. \
Every topic from every source document must appear — nothing should be \
silently dropped. You have room to keep detail — use it for the patterns \
that prevent the most common AI coding mistakes.

SECTIONS THAT NEED DEPTH (don't over-compress these):
- Error handling: keep the multi-language patterns (Python, Go, Rust, TS, Bash)
- Config cascade: keep the .env rules AND at least one language example
- Testing: keep the full no-mocks table, testcontainers example, real binary pattern
- Git: keep the full commit type table and branch flow
- Security: keep all OWASP prevention patterns with code examples
- Logging: keep the structured logging fields and masking rules
- AI Conduct: keep SEP field rules AND the banned phrases table

SOURCE DOCUMENTS (concatenated from {file_count} files):
"""


def _load_anthropic_api_key() -> Optional[str]:
    """Load ANTHROPIC_API_KEY from environment or .env file."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if key:
        return key
    env_file = REPO_ROOT / ".env"
    if env_file.is_file():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("ANTHROPIC_API_KEY="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return None


def compress_with_llm(
    body: str, source_path: Path, verbose: bool
) -> tuple[str, list[str]]:
    """Compress a source standard using Claude API.

    Returns (compressed_markdown, warnings). On failure returns ("", warnings).
    """
    try:
        from anthropic import Anthropic
    except ImportError:
        return "", [
            f"{source_path.name}: anthropic SDK not installed (pip install anthropic)"
        ]

    api_key = _load_anthropic_api_key()
    if not api_key:
        msg = (
            f"{source_path.name}: ANTHROPIC_API_KEY not found"
            " — skipping LLM compression"
        )
        return "", [msg]

    client = Anthropic(api_key=api_key)
    warnings: list[str] = []

    if verbose:
        print(f"    LLM compressing {source_path.name}...", end="", flush=True)

    try:
        # Use streaming to avoid timeout on large outputs
        chunks: list[str] = []
        with client.messages.stream(
            model="claude-opus-4-6",
            max_tokens=32768,
            messages=[
                {
                    "role": "user",
                    "content": _LLM_COMPRESS_PROMPT + body,
                }
            ],
        ) as stream:
            for text in stream.text_stream:
                chunks.append(text)
        response = stream.get_final_message()
    except Exception as exc:
        msg = f"{source_path.name}: LLM call failed: {exc}"
        if verbose:
            print(f" FAILED: {exc}")
        return "", [msg]

    compressed = "".join(chunks).strip()

    # Strip markdown fences if the model wrapped the output
    if compressed.startswith("```"):
        first_nl = compressed.index("\n") + 1
        compressed = compressed[first_nl:]
    if compressed.endswith("```"):
        compressed = compressed[:-3].rstrip()

    lines = compressed.splitlines()

    if verbose:
        tokens_in = response.usage.input_tokens
        tokens_out = response.usage.output_tokens
        print(f" done ({len(lines)} lines, {tokens_in}\u2192{tokens_out} tokens)")

    return compressed + "\n", warnings


# ---------------------------------------------------------------------------
# Combined universal compression
# ---------------------------------------------------------------------------

UNIVERSAL_RULES_NAME = "universal.md"


def process_universal_combined(check: bool, verbose: bool) -> tuple[int, int]:
    """Combine all universal/*.md into a single compact universal.md.

    This produces the always-on baseline rule file with NO path scoping,
    ensuring it loads on every conversation regardless of file context.

    Returns (errors, warnings) counts.
    """
    errors = 0
    warnings_count = 0
    rules_path = RULES_DIR / UNIVERSAL_RULES_NAME

    if not UNIVERSAL_SOURCE_DIR.is_dir():
        if verbose:
            print("  SKIP universal combined — directory not found")
        return 0, 0

    source_files = sorted(UNIVERSAL_SOURCE_DIR.glob("*.md"))
    if not source_files:
        if verbose:
            print("  SKIP universal combined — no source files")
        return 0, 0

    if check:
        if rules_path.exists():
            if verbose:
                print(f"  OK   {UNIVERSAL_RULES_NAME} (combined)")
        else:
            print(
                f"  WARN {UNIVERSAL_RULES_NAME} — missing"
                " (run generate-rules.py --force)",
                file=sys.stderr,
            )
            warnings_count += 1
        return errors, warnings_count

    # Concatenate all universal source files with headers
    parts: list[str] = []
    file_names: list[str] = []
    for src in source_files:
        text = src.read_text(encoding="utf-8")
        _, body = parse_frontmatter(text)
        if body.strip():
            parts.append(f"# === SOURCE: {src.name} ===\n\n{body}")
            file_names.append(src.name)

    if not parts:
        if verbose:
            print("  SKIP universal combined — all source files empty")
        return 0, 0

    combined_body = "\n\n".join(parts)
    prompt = _UNIVERSAL_COMBINED_PROMPT.format(file_count=len(parts))

    if verbose:
        print(
            f"    LLM compressing {len(parts)} universal files"
            " into combined universal.md...",
            end="",
            flush=True,
        )

    try:
        from anthropic import Anthropic
    except ImportError:
        msg = "universal combined: anthropic SDK not installed"
        print(f"  WARN {msg}", file=sys.stderr)
        return 0, 1

    api_key = _load_anthropic_api_key()
    if not api_key:
        msg = "universal combined: ANTHROPIC_API_KEY not found — skipping"
        print(f"  WARN {msg}", file=sys.stderr)
        return 0, 1

    client = Anthropic(api_key=api_key)

    try:
        chunks: list[str] = []
        with client.messages.stream(
            model="claude-opus-4-6",
            max_tokens=32768,
            messages=[
                {
                    "role": "user",
                    "content": prompt + combined_body,
                }
            ],
        ) as stream:
            for text in stream.text_stream:
                chunks.append(text)
        response = stream.get_final_message()
    except Exception as exc:
        msg = f"universal combined: LLM call failed: {exc}"
        if verbose:
            print(f" FAILED: {exc}")
        print(f"  WARN {msg}", file=sys.stderr)
        return 0, 1

    compressed = "".join(chunks).strip()

    # Strip markdown fences if the model wrapped the output
    if compressed.startswith("```"):
        first_nl = compressed.index("\n") + 1
        compressed = compressed[first_nl:]
    if compressed.endswith("```"):
        compressed = compressed[:-3].rstrip()

    if not compressed.strip():
        print(
            "  SKIP universal combined — LLM returned empty (keeping existing)",
            file=sys.stderr,
        )
        return 0, 1

    output_lines = compressed.splitlines()

    if verbose:
        tokens_in = response.usage.input_tokens
        tokens_out = response.usage.output_tokens
        print(
            f" done ({len(output_lines)} lines, {tokens_in}\u2192{tokens_out} tokens)"
        )

    # Build the universal rules file — NO paths, NO detect_markers
    # This ensures it always loads on every conversation
    source_list = ", ".join(file_names)
    header_lines = [
        "---",
        f"# {GENERATED_MARKER}",
        f"# Source: standards/universal/ ({len(parts)} files: {source_list})",
        "# Regenerate with: python tools/generate-rules.py --force",
        "#",
        "# NO paths or detect_markers — this file loads on EVERY conversation",
        "# as the universal baseline. Language/infra rules load separately.",
        "source: universal/",
        "---",
        "",
        compressed,
        "",
    ]
    new_content = "\n".join(header_lines)
    rules_path.write_text(new_content, encoding="utf-8")

    if verbose:
        print(f"  GEN  {UNIVERSAL_RULES_NAME} (combined from {len(parts)} files)")

    return errors, warnings_count


# ---------------------------------------------------------------------------
# Rules file generation
# ---------------------------------------------------------------------------


def build_rules_file(meta: dict, body: str, source_rel: str) -> str:
    """Build the full content of a generated rules file."""
    lines = ["---"]
    lines.append(f"# {GENERATED_MARKER}")
    lines.append(f"# Source: standards/{source_rel}")
    lines.append(
        "# Regenerate with: python tools/generate-rules.py --file "
        + Path(source_rel).name
    )

    detect_markers = meta.get("detect_markers", [])

    # If detect_markers include project-level file markers, the rule is
    # project-wide and should load unconditionally (no paths restriction).
    # The detect_markers tell claude.sh which projects to symlink the rule
    # into — once symlinked, it should always load.
    has_project_markers = any(
        m.startswith("file:") or m.startswith("dir:") for m in detect_markers
    )

    rule_paths = meta.get("rule_paths") or meta.get("paths", [])
    if rule_paths and not has_project_markers:
        lines.append("paths:")
        for p in rule_paths:
            lines.append(f'  - "{p}"')
    elif has_project_markers:
        lines.append("# NO paths — project-wide rule (detect_markers matched project files)")

    if detect_markers:
        lines.append("detect_markers:")
        for m in detect_markers:
            lines.append(f'  - "{m}"')

    lines.append(f"source: {source_rel}")
    lines.append("---")
    lines.append("")
    lines.append(body)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Stem → rules filename mapping
# ---------------------------------------------------------------------------


def source_to_rules_name(source_path: Path) -> str:
    """Convert source filename to rules filename (lowercase).

    Direct 1:1 mapping: RUST.md → rust.md, SQL-CLICKHOUSE.md → sql-clickhouse.md.
    No lookup table — just lowercase the stem.
    """
    return f"{source_path.stem.lower()}.md"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def process_file(
    source_path: Path,
    check: bool,
    verbose: bool,
) -> tuple[int, int]:
    """Process one source file. Returns (errors, warnings) counts."""
    errors = 0
    warnings_count = 0

    text = source_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)

    if not meta:
        if verbose:
            print(f"  SKIP {source_path.name} — no frontmatter")
        return 0, 0

    rules_name = source_to_rules_name(source_path)
    rules_path = RULES_DIR / rules_name

    if check:
        # Check mode: validate frontmatter structure only.
        # We do NOT compare content — LLM output is non-deterministic.
        if rules_path.exists():
            if verbose:
                print(f"  OK   {rules_name}")
        else:
            print(
                f"  WARN {rules_name} — missing (run generate-rules.py)",
                file=sys.stderr,
            )
            warnings_count += 1
        return errors, warnings_count

    # Carry forward paths/detect_markers from existing rule file
    # (source frontmatter defines these; existing rules may also have them)
    if rules_path.exists():
        existing_meta, _ = parse_frontmatter(rules_path.read_text(encoding="utf-8"))
        for key in ("paths", "rule_paths", "detect_markers"):
            if key not in meta and key in existing_meta:
                meta[key] = existing_meta[key]

    # Generate mode: compress with LLM
    compressed, llm_warnings = compress_with_llm(body, source_path, verbose)
    for w in llm_warnings:
        print(f"  WARN {w}", file=sys.stderr)
        warnings_count += 1

    if not compressed.strip():
        print(
            f"  SKIP {rules_name} — LLM compression returned empty (keeping existing)",
            file=sys.stderr,
        )
        return errors, warnings_count

    try:
        source_rel = source_path.relative_to(STANDARDS_DIR).as_posix()
    except ValueError:
        source_rel = source_path.name

    new_content = build_rules_file(meta, compressed, source_rel)
    rules_path.write_text(new_content, encoding="utf-8")
    if verbose:
        warn_str = f" ({warnings_count} warnings)" if warnings_count else ""
        print(f"  GEN  {rules_name}{warn_str}")

    return errors, warnings_count


def _get_changed_sources(base_ref: str = "HEAD~1") -> set[Path]:
    """Find source standards changed since base_ref using git diff.

    Returns set of absolute Paths to changed/added source files.
    Scans SOURCE_DIRS (languages, infrastructure) for individual rules
    AND UNIVERSAL_SOURCE_DIR for combined universal.md detection.
    Also handles deletions: removes compact rules for deleted sources.
    """
    import subprocess

    changed: set[Path] = set()
    deleted_sources: list[Path] = []

    # Scan individual rule dirs + universal dir for changes
    all_dirs = list(SOURCE_DIRS) + [UNIVERSAL_SOURCE_DIR]
    for source_dir in all_dirs:
        if not source_dir.is_dir():
            continue
        try:
            rel = source_dir.relative_to(REPO_ROOT)
        except ValueError:
            continue

        # Changed or added files
        result = subprocess.run(
            [
                "git",
                "diff",
                "--name-only",
                "--diff-filter=ACM",
                base_ref,
                "--",
                str(rel),
            ],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )
        if result.returncode == 0:
            for line in result.stdout.strip().splitlines():
                if line.endswith(".md"):
                    changed.add(REPO_ROOT / line)

        # Deleted files
        result = subprocess.run(
            ["git", "diff", "--name-only", "--diff-filter=D", base_ref, "--", str(rel)],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
        )
        if result.returncode == 0:
            for line in result.stdout.strip().splitlines():
                if line.endswith(".md"):
                    deleted_sources.append(REPO_ROOT / line)

    # Remove compact rules for deleted sources
    for deleted in deleted_sources:
        rules_name = source_to_rules_name(deleted)
        rules_path = RULES_DIR / rules_name
        if rules_path.exists():
            rules_path.unlink()
            print(f"  DEL  {rules_name} (source {deleted.name} removed)")

    return changed


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    verbose = "--verbose" in args or "-v" in args
    force = "--force" in args
    file_filter = None
    if "--file" in args:
        idx = args.index("--file")
        if idx + 1 < len(args):
            file_filter = args[idx + 1]

    # --file UNIVERSAL targets only the combined universal rule
    universal_only = file_filter and file_filter.upper() == "UNIVERSAL"

    # Default: only changed files. --force or --file: process all/specific.
    changed_set: set[Path] = set()
    delta_mode = not force and not file_filter and not check
    if delta_mode:
        changed_set = _get_changed_sources()
        if verbose:
            if changed_set:
                names = ", ".join(p.name for p in changed_set)
                print(f"Changed sources: {names}")
            else:
                print("No changed sources — nothing to do.")

    total_errors = 0
    total_warnings = 0
    total_processed = 0

    # --- Combined universal.md (always-on baseline) ---
    # Triggers when: --force, --file UNIVERSAL, check mode, or any
    # universal/ file changed in delta mode.
    universal_changed = any(str(UNIVERSAL_SOURCE_DIR) in str(p) for p in changed_set)
    should_process_universal = (
        check or force or universal_only or (delta_mode and universal_changed)
    )

    if should_process_universal:
        if verbose and not check:
            print("  Processing combined universal.md...")
        errors, warns = process_universal_combined(check=check, verbose=verbose)
        total_errors += errors
        total_warnings += warns
        total_processed += 1

    # --- Individual per-topic rules ---
    if not universal_only:
        for source_dir in SOURCE_DIRS:
            if not source_dir.is_dir():
                continue
            for source_path in sorted(source_dir.glob("*.md")):
                if file_filter and source_path.name != file_filter:
                    continue
                if delta_mode and source_path not in changed_set:
                    continue
                errors, warns = process_file(source_path, check=check, verbose=verbose)
                total_errors += errors
                total_warnings += warns
                total_processed += 1

    if verbose or total_errors:
        mode = "CHECK" if check else "GENERATE"
        print(
            f"\n[{mode}] {total_processed} files"
            f" | {total_errors} errors"
            f" | {total_warnings} warnings"
        )

    return 1 if total_errors else 0


if __name__ == "__main__":
    sys.exit(main())
